backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "documento"
    label: "Documento Web"
    files:
      - file: "index.html"
        label: "Hoja Principal"
        name: "principal"
        fields:
          - {label: "Contenido del Documento", name: "cuerpo", widget: "markdown"}