backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "paginas"
    label: "Páginas de la Web"
    files:
      - file: "index.html"
        label: "Página Principal (Contacto Vitall)"
        name: "home"
        fields:
          - {label: "Título de la Empresa", name: "titulo", widget: "string"}
          - label: "Contenido Libre (Estilo Word)"
            name: "contenido_libre"
            widget: "markdown"